//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hermes.Server.Api.Infrastructure.Persistence.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class DictionaryProvider {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal DictionaryProvider() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Hermes.Server.Api.Infrastructure.Persistence.Resources.DictionaryProvider", typeof(DictionaryProvider).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to a
        ///aa
        ///aaa
        ///aachen
        ///aardvark
        ///aardvarks
        ///aardwolf
        ///aardwolves
        ///aarhus
        ///aaron
        ///aaronic
        ///aaronical
        ///aasvogel
        ///aasvogels
        ///ab
        ///aba
        ///ababa
        ///abac
        ///abaca
        ///abacas
        ///abaci
        ///aback
        ///abacs
        ///abactinal
        ///abactinally
        ///abactor
        ///abactors
        ///abacus
        ///abacuses
        ///abadan
        ///abaddon
        ///abaft
        ///abalone
        ///abalones
        ///abampere
        ///abamperes
        ///aband
        ///abandon
        ///abandoned
        ///abandonedly
        ///abandonee
        ///abandonees
        ///abandoning
        ///abandonment
        ///abandonments
        ///abandons
        ///abas
        ///abase
        ///abased
        ///abasement
        ///abasements
        ///abases
        ///abash
        ///abashed
        ///abashedly
        ///abashes
        ///abashing
        /// [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Words {
            get {
                return ResourceManager.GetString("Words", resourceCulture);
            }
        }
    }
}
