name: 'server-api: deploy'

on: # only run this action when a pr is merged to a feature or hot-fix branch
  push:
    branches:
      - 'main'
    paths:
      - '.github/workflows/server-api*'
      - 'server-api/**'
      - '!server-api/**/*.md'

jobs:
  build-and-deploy:
    name: Build and Deploy 'server-api' to Google Cloud Run
    runs-on: ubuntu-latest
    environment: production
    steps:
      - name: checkout hermes repository
        uses: actions/checkout@v2
